### ISSUE TITLE
Does not work when compiled in windows, just gives a bunch of arrows instead of colors

### ISSUE THREAD

**Issue by Darshan-2021-11** [Terraminator/color_escape#1]

**Comment by Terraminator** [comment]
Could you please provide more information on linux it works just fine. I will later test for windows but as i developed this on windows it should work too.

**Comment by Terraminator** [comment]
ok i tested and it works on windows too.

**Comment by Darshan-2021-11** [comment]
Sorry for the lack of information given by me... So, the problem comes out to be a specific instance of using mingw to compile the code instead of the usual visual studio. This results in a lack of color like this

**Comment by Darshan-2021-11** [comment]
This is how the one looks
![Screenshot (583)](https://github.com/Terraminator/color_escape/assets/94628638/05d56200-9b48-4042-8689-0b82c3284035)

**Comment by Terraminator** [comment]
you are right this issue is specific to mingw, i was able to reproduce the issue with g++(MinGW.org GCC-6.3.0-1) 6.3.0. You can still see the output if you launch the executable with explorer. You can do this via cmd with `explorer main.exe`. This should give you colored output. This problem seems to be related to the parent terminal's flags. I will try to set the flag for the current console context to fix this. Till then you can use the explorer workaround

**Comment by Darshan-2021-11** [comment]
If you are talking about opening cmd.exe from explorer's address bar, then opening the desired executable, it still does not work for me. But I got some work arounds this. This involves changing some dword value (possibly also adding a registry edit) in registry editor of windows.

If you go to the `Computer\HKEY_CURRENT_USER\Console`
and check for VirtualTerminalLevel, you might see the dword or not, but if you add and set its value to 1, then you could see the window generated by mingw in colored text using ANSI codes...

I don't know why, but you would help me identify why this is the case, and how can I make this behaviour replicate in my production code, and will not affect my clients in any way, it would be very useful...

Thanks again for helping.

**Comment by Darshan-2021-11** [comment]
![Screenshot (584)](https://github.com/Terraminator/color_escape/assets/94628638/13164706-21b2-4442-8f10-c62953f579d7)

**Comment by Terraminator** [comment]
what i meant for the workaround was opening cmd.exe ( by pressing win+r and typing cmd.exe) and then changing the current working directory to point to the one where your executable is (for example: cd C:/Users/Username/Downloads/color_escape) and then compile the script by doing: g++ main.c -o main.exe. After that you just need to run "explorer main.exe" in cmd

**Comment by Terraminator** [comment]
would you mind talking over discord? this would save some time
my dc: TERRAMINATOR#1575

**Comment by Darshan-2021-11** [comment]
> what i meant for the workaround was opening cmd.exe ( by pressing win+r and typing cmd.exe) and then changing the current working directory to point to the one where your executable is (for example: cd C:/Users/Username/Downloads/color_escape) and then compile the script by doing: g++ main.c -o main.exe. After that you just need to run "explorer main.exe" in cmd

Just tried, does not work for me...

**Comment by Terraminator** [comment]
ok. then wait for the fix, i think i can attach a console and set the ENABLE_PROCESSED_OUTPUT  flag manually
